### ISSUE TITLE
["Request"] Guava integration

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-fx#155]
What would you like to see?

An integration for Guava's `ListenableFuture`.

See [KotlinX Coroutine Guava](https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-guava)  for an example implementation.

**Comment by abendt** [comment]
i worked a bit on that to learn more about arrow and fp.
i was able to implement some typeclass instances for ListenableFuture: https://github.com/abendt/arrow-fx/blob/guava/arrow-fx-guava/src/main/kotlin/arrow/fx/guava/extensions/listenablefuturek.kt

I could not come up with a law conforming ApplicativeError instance. If i understand it correctly this is because the ListenableFuture will communicate the Error by throwing exceptions, thereby breaking referential transparency. Is this conclusion correct?

**Comment by pakoito** [comment]
Isn't there something like `hasFailed` and `getError`, or is the API just `getOrThrow`?

**Comment by abendt** [comment]
as far as i understand there is just the _get()_ method that will throw when the underlying compuation failed.

see https://guava.dev/releases/21.0/api/docs/com/google/common/util/concurrent/ListenableFuture.html

**Comment by nomisRev** [comment]
Obsolete by KotlinX Coroutines
