### ISSUE TITLE
["Request"] Stream callback testing

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow-fx#239]
What would you like to see?

- More negative tests for callback Streams.
- A way to avoid sending events after calling end() on the stream

see: https://github.com/arrow-kt/arrow-fx/pull/199#discussion_r462509205

**Comment by pablisco** [comment]
> There is no way to avoid sending events after end.
Since I wrote this I've discovered `CancelToken` 😗👌

I guess that it may still be worth deciding what to do when we try to emit something and the stream is closed. It would be a bit of a breaking change, but my suggestion is to have `emit` fail with an exception and have the same set of functions called `offer` that are more lenient.

Either way, for the negative tests I was mostly talking about verifying (even if it's nothing) the behaviour of signalling after closure.

**Comment by nomisRev** [comment]
> It would be a bit of a breaking change
Nothing is released yet, so that's not a concern. We need to make all streamline all APIs before releasing them.

Sending an exception after closing is fine.
The only other option would be to expose the `Queue` API, which would be more in line with KotlinX's callbackFlow API. That, however, would push the responsibility of writing closing logic on the user. On the other hand, this would make our a first unsafe API :(

For comparison in `IO.async` we ignore subsequent emissions instead of throwing an exception.

Another option would be to expose `:Boolean` to the user which is now possible with #246.

**Comment by pablisco** [comment]
I'm thinking, given that we have `cancellable {}` I'm wondering if we need to have `callback {}`. We could have `CancelToken.unit` to return a token that doesn't do anything keeping the API typesafe 🤔 i.e. what do we get extra from the callback API?

**Comment by nomisRev** [comment]
Closed due to obsolete

**Comment by nomisRev** [comment]
Closed due to obsolete

**Comment by nomisRev** [comment]
Closed due to obsolete
